### ISSUE TITLE
Add optional fields to Create Item

### ISSUE THREAD

**Issue by htoo97** [UCSDTESC/inventory#4]
Take a look at the [InventoryItem type](https://github.com/UCSDTESC/inventory/blob/master/src/shared/Types.ts#L7) and the design doc on slack for the schema. We want to have all fields clearly denoted as either required or optional. If required, it should raise an error when the user tries to create the item without filling it in. This is for the [admin's create view](https://github.com/UCSDTESC/inventory/blob/master/src/client/pages/NewItemPage/components/NewItemForm.tsx).

**Comment by subhankar-panda** [comment]
I added Picture uploads earlier today, you should be able to work off of that code to add receipts (which should follow the same model, an image taken / uploaded that gets uploaded to GCS (Google Cloud Storage) and with the url to the img  saved in firebase.

**Comment by subhankar-panda** [comment]
sorry for any merge conflicts :( lmk on slack if you any need help fixing them @vickivc
